clinicmgmt/blueprints/administration.py
from flask import Blueprint, request, redirect, url_for, render_template

from clinicmgmt.reusables.context import db_cursor
from clinicmgmt.reusables.context import db_connection
from clinicmgmt.reusables.context import website_context
from clinicmgmt.reusables.context import LANG_STRINGS
from clinicmgmt.reusables.user_validation import get_user_context
from clinicmgmt.reusables.constants import ALL_TIMEZONES
from clinicmgmt.reusables.constants import SUPPORTED_LANGUAGES

from clinicmgmt.classes.WebsiteConfig import *

administration = Blueprint("administration", __name__)


@administration.route('/administration')
def admin():
    user_context = get_user_context()
    if not user_context:
        return redirect(url_for("user_management.login_form"))
    if not user_context.is_administrator == 1:
        return LANG_STRINGS.ONLY_ADMINISTRATOR_HAS_THE_PERMISSIONS_TO_DO_THIS

    return render_template(
        "admin_panel.html",
        WEBSITE_CONTEXT=website_context,
        USER_CONTEXT=user_context,
        LANG_STRINGS=LANG_STRINGS
    )


@administration.route('/administration/sql_form')
def sql_form():
    user_context = get_user_context()
    if not user_context:
        return redirect(url_for("user_management.login_form"))
    if not user_context.is_administrator == 1:
        return LANG_STRINGS.ONLY_ADMINISTRATOR_HAS_THE_PERMISSIONS_TO_DO_THIS

    return render_template(
        "sql.html",
        WEBSITE_CONTEXT=website_context,
        USER_CONTEXT=user_context,
        LANG_STRINGS=LANG_STRINGS
    )


@administration.route('/administration/sql_exec', methods=['POST'])
def sql_exec():
    user_context = get_user_context()
    if not user_context:
        return redirect(url_for("user_management.login_form"))
    if not user_context.is_administrator == 1:
        return LANG_STRINGS.ONLY_ADMINISTRATOR_HAS_THE_PERMISSIONS_TO_DO_THIS

    if request.method == 'POST':
        sql_query = request.form['sql_query']

        sql_results = tuple(db_cursor.execute(sql_query))
        db_connection.commit()

        return render_template(
            "sql.html",
            WEBSITE_CONTEXT=website_context,
            USER_CONTEXT=user_context,
            SQL_RESULTS=sql_results,
            LANG_STRINGS=LANG_STRINGS
        )


@administration.route('/user_list')
def user_listing():
    user_context = get_user_context()
    if not user_context:
        return redirect(url_for("user_management.login_form"))
    # if not user_context.is_administrator == 1:
    #     return LANG_STRINGS.ONLY_ADMINISTRATOR_HAS_THE_PERMISSIONS_TO_DO_THIS

    info_db = tuple(db_cursor.execute("SELECT id, email, display_name, is_administrator, is_approver FROM users"))
    return render_template(
        "user_listing.html",
        WEBSITE_CONTEXT=website_context,
        USER_LISTING=info_db,
        USER_CONTEXT=user_context,
        LANG_STRINGS=LANG_STRINGS
    )


@administration.route('/website_configuration_form')
def website_configuration_form():
    user_context = get_user_context()
    if not user_context:
        return redirect(url_for("user_management.login_form"))
    if not user_context.is_administrator == 1:
        return LANG_STRINGS.ONLY_ADMINISTRATOR_HAS_THE_PERMISSIONS_TO_DO_THIS

    config_db = tuple(db_cursor.execute("SELECT setting, value FROM app_configuration"))

    config = WebsiteConfig(config_db)

    return render_template(
        "admin_website_configuration_form.html",
        WEBSITE_CONTEXT=website_context,
        CONFIG=config,
        USER_CONTEXT=user_context,
        ALL_TIMEZONES=ALL_TIMEZONES,
        SUPPORTED_LANGUAGES=SUPPORTED_LANGUAGES,
        LANG_STRINGS=LANG_STRINGS
    )


@administration.route('/update_website_config', methods=['POST'])
def update_website_config():
    user_context = get_user_context()
    if not user_context:
        return redirect(url_for("user_management.login_form"))
    if not user_context.is_administrator == 1:
        return LANG_STRINGS.ONLY_ADMINISTRATOR_HAS_THE_PERMISSIONS_TO_DO_THIS

    title = request.form['title']
    timezone_str = request.form['timezone_str']
    language = request.form['language']

    db_cursor.execute("INSERT OR REPLACE INTO app_configuration (setting, value) VALUES (?, ?)", ["title", title])

    db_cursor.execute("INSERT OR REPLACE INTO app_configuration (setting, value) VALUES (?, ?)",
                      ["timezone_str", timezone_str])

    db_cursor.execute("INSERT OR REPLACE INTO app_configuration (setting, value) VALUES (?, ?)",
                      ["language", language])

    db_connection.commit()

    return render_template(
        "admin_panel.html",
        WEBSITE_CONTEXT=website_context,
        USER_CONTEXT=user_context,
        NOTICE_MESSAGE=LANG_STRINGS.CONFIG_SAVED_RESTART_TO_APPLY,
        ALERT_TYPE="alert-info",
        LANG_STRINGS=LANG_STRINGS
    )

clinicmgmt/blueprints/schedule.py
import uuid
from datetime import datetime
import time

from flask import Blueprint, request, make_response, redirect, url_for, render_template

from clinicmgmt.reusables.context import db_cursor
from clinicmgmt.reusables.context import db_connection
from clinicmgmt.reusables.context import website_context
from clinicmgmt.reusables.context import LANG_STRINGS
from clinicmgmt.reusables.user_validation import get_user_context

from clinicmgmt.classes.Entry import Entry
from clinicmgmt.classes.EntryAuthor import EntryAuthor
from clinicmgmt.classes.EntryDeletedAuthor import EntryDeletedAuthor

schedule = Blueprint("schedule", __name__)


@schedule.route('/', methods=['GET', 'POST'], endpoint="index")
@schedule.route('/printable', methods=['GET', 'POST'], endpoint="index_printable")
def index():
    user_context = get_user_context()
    if not user_context:
        return redirect(url_for("user_management.login_form"))

    timeframe = request.args.get('timeframe', "72hour")
    timeframe_str = LANG_STRINGS.OPERATIONS

    if request.method == 'POST':
        args_to_forward = request.form.to_dict()
    else:
        args_to_forward = request.args.to_dict()

    if timeframe == "search":
        args_to_forward["timeframe"] = "search"
    elif timeframe == "all":
        args_to_forward["timeframe"] = "all"

    author_id = request.form.get('author_id', request.args.get('author_id', ""))
    patient_name = request.form.get('patient_name', request.args.get('patient_name', ""))
    assigned_doctor_id = request.form.get('assigned_doctor_id', request.args.get('assigned_doctor_id', ""))
    assigned_doctor_name = request.form.get('assigned_doctor_name', request.args.get('assigned_doctor_name', ""))
    year_month = request.form.get('year_month', request.args.get('year_month', ""))
    html_timestamp = request.form.get('timestamp', request.args.get('timestamp', ""))
    type_of_surgery = request.form.get('type_of_surgery', request.args.get('type_of_surgery', ""))
    patient_birth_year = request.form.get('patient_birth_year', request.args.get('patient_birth_year', ""))
    patient_phone_number = request.form.get('patient_phone_number', request.args.get('patient_phone_number', ""))
    has_consultation_happened = request.form.get('has_consultation_happened',
                                                 request.args.get('has_consultation_happened', ""))

    base_query = ("SELECT id, author_id, last_edit_author_id, assigned_doctor_id, assigned_doctor_name, "
                  "patient_name, scheduled_timestamp, added_timestamp, last_edited_timestamp, type_of_surgery, "
                  "diagnosis, patient_birth_year, patient_phone_number, has_consultation_happened, "
                  "is_completed FROM patient_entries")

    where_conditions = []
    params = []

    if len(author_id) > 0:
        where_conditions.append("author_id = ?")
        params.append(author_id)

    if len(patient_name) > 0:
        where_conditions.append("patient_name LIKE ?")
        params.append("%" + patient_name + "%")

    if len(assigned_doctor_id) > 0:
        where_conditions.append("assigned_doctor_id = ?")
        params.append(assigned_doctor_id)

    if len(assigned_doctor_name) > 0:
        where_conditions.append("assigned_doctor_name LIKE ?")
        params.append("%" + assigned_doctor_name + "%")

    if len(type_of_surgery) > 0:
        where_conditions.append("type_of_surgery = ?")
        params.append(type_of_surgery)

    if len(patient_birth_year) > 0:
        where_conditions.append("patient_birth_year = ?")
        params.append(patient_birth_year)

    if len(patient_phone_number) > 0:
        where_conditions.append("patient_phone_number LIKE ?")
        params.append("%" + patient_phone_number + "%")

    if len(has_consultation_happened) > 0:
        where_conditions.append("has_consultation_happened = ?")
        params.append(has_consultation_happened)

    if timeframe == "72hour":
        time_now = time.time()

        where_conditions.append("scheduled_timestamp > ?")
        params.append((time_now - 86400))
        start_timestamp_obj = datetime.fromtimestamp((time_now - 86400), tz=website_context['timezone'])
        start_timestamp_str = start_timestamp_obj.strftime("%Y-%m-%d %H:%M")

        where_conditions.append("scheduled_timestamp < ?")
        params.append((time_now + 86400))
        end_timestamp_obj = datetime.fromtimestamp((time_now + 86400), tz=website_context['timezone'])
        end_timestamp_str = end_timestamp_obj.strftime("%Y-%m-%d %H:%M")

        timeframe_str = f"{start_timestamp_str} - {end_timestamp_str}"
    elif timeframe == "all":
        timeframe_str = LANG_STRINGS.ARCHIVE_AND_FUTURE
    else:
        timeframe_str = LANG_STRINGS.SEARCH_RESULTS

        if len(html_timestamp) > 0:
            where_conditions.append("scheduled_timestamp > ?")
            start_scheduled_timestamp_input_datetime = (datetime.strptime(html_timestamp + "T00:00:00" +
                                                                          website_context['timezone_str'],
                                                                          "%Y-%m-%dT%H:%M:%S%z"))
            start_scheduled_timestamp = int(start_scheduled_timestamp_input_datetime.timestamp())
            params.append(start_scheduled_timestamp - 1)

            where_conditions.append("scheduled_timestamp < ?")
            end_scheduled_timestamp_input_datetime = (datetime.strptime(html_timestamp + "T23:59:59" +
                                                                        website_context['timezone_str'],
                                                                        "%Y-%m-%dT%H:%M:%S%z"))
            end_scheduled_timestamp = int(end_scheduled_timestamp_input_datetime.timestamp())
            params.append(end_scheduled_timestamp + 1)

            timeframe_str = (f"{start_scheduled_timestamp_input_datetime.strftime('%Y-%m-%d %H:%M')} - "
                             f"{end_scheduled_timestamp_input_datetime.strftime('%Y-%m-%d %H:%M')}")

        if len(year_month) > 0:
            where_conditions.append("scheduled_timestamp > ?")
            start_scheduled_timestamp_input_datetime = (datetime.strptime(year_month + "-01T00:00:00" +
                                                                          website_context['timezone_str'],
                                                                          "%Y-%m-%dT%H:%M:%S%z"))
            start_scheduled_timestamp = int(start_scheduled_timestamp_input_datetime.timestamp())
            params.append(start_scheduled_timestamp - 1)

            where_conditions.append("scheduled_timestamp < ?")
            end_scheduled_timestamp_input_datetime = (datetime.strptime(year_month + "-28T23:59:59" +
                                                                        website_context['timezone_str'],
                                                                        "%Y-%m-%dT%H:%M:%S%z"))
            end_scheduled_timestamp = int(end_scheduled_timestamp_input_datetime.timestamp())

            if end_scheduled_timestamp_input_datetime.month in [1, 3, 5, 7, 8, 10, 12]:  # 31 day months
                append = 259200
            elif end_scheduled_timestamp_input_datetime.month in [4, 6, 9, 11]:  # 30 day months
                append = 172800
            elif end_scheduled_timestamp_input_datetime.month == 2:  # february :(
                year = end_scheduled_timestamp_input_datetime.year
                if (year % 400 == 0) or (year % 100 != 0) and (year % 4 == 0): # is leap year
                    append = 86400
                else:
                    append = 0
            else:
                append = 259200

            params.append(end_scheduled_timestamp + append + 1)
            timeframe_str = (f"{start_scheduled_timestamp_input_datetime.strftime('%Y-%m-%d %H:%M')} - "
                             f"{end_scheduled_timestamp_input_datetime.strftime('%Y-%m-%d %H:%M')}")
            # TODO: only 28 days show up, fix.

    if where_conditions:
        where_clause = " WHERE " + " AND ".join(where_conditions)
    else:
        where_clause = ""

    final_query = base_query + where_clause + " ORDER BY scheduled_timestamp ASC"

    print(final_query)
    entry_db_lookup = tuple(db_cursor.execute(final_query, params))

    entries = []
    for entry in entry_db_lookup:
        current_entry = Entry(entry)
        current_entry_author = tuple(db_cursor.execute("SELECT id, email, display_name, is_administrator, is_approver "
                                                       "FROM users WHERE id = ?", [current_entry.author_id]))
        if current_entry_author:
            current_entry.author = EntryAuthor(current_entry_author[0])
        else:
            current_entry.author = EntryDeletedAuthor(current_entry.author_id)
        entries.append(current_entry)

    if request.endpoint == "schedule.index_printable":
        print_timestamp_obj = datetime.fromtimestamp((time.time() + 86400), tz=website_context['timezone'])
        print_timestamp_str = print_timestamp_obj.strftime("%Y-%m-%d %H:%M")
        return make_response(
            render_template(
                "entry_listing_printable.html",
                WEBSITE_CONTEXT=website_context,
                USER_CONTEXT=user_context,
                ENTRIES=entries,
                TIMEFRAME_STR=timeframe_str,
                PRINT_TIMESTAMP_STR=print_timestamp_str,
                LANG_STRINGS=LANG_STRINGS
            )
        )
    else:
        return make_response(
            render_template(
                "entry_listing.html",
                WEBSITE_CONTEXT=website_context,
                USER_CONTEXT=user_context,
                ENTRIES=entries,
                TIMEFRAME_STR=timeframe_str,
                ARGS_TO_FORWARD=args_to_forward,
                LANG_STRINGS=LANG_STRINGS
            )
        )


@schedule.route('/entry_maker_form')
def entry_maker_form():

clinicmgmt/templates/account_settings.html
{% extends "base.html" %}

{% block HTML_CONTENTS %}
    <div class="container">
        <h1>{{ LANG_STRINGS.ACCOUNT_SETTINGS }}</h1>
        <a href="{{ url_for("user_management.change_password_form") }}" class="btn btn-danger my-1">{{ LANG_STRINGS.CHANGE_PASSWORD }}</a><br>
        <a href="{{ url_for("user_management.session_listing_page") }}" class="btn btn-primary my-1">{{ LANG_STRINGS.SESSION_MANAGEMENT }}</a><br>
    </div>
{% endblock %}

clinicmgmt/templates/admin_panel.html
{% extends "base.html" %}

{% block HTML_CONTENTS %}
    <div class="container">
        <h1>{{ LANG_STRINGS.ADMINISTRATION }}</h1>
        <a href="{{ url_for("administration.website_configuration_form") }}" class="btn btn-primary my-1">{{ LANG_STRINGS.WEB_PORTAL_CONFIGURATION }}</a><br>
        <a href="{{ url_for("administration.sql_form") }}" class="btn btn-primary my-1">{{ LANG_STRINGS.SQL_CONSOLE }}</a><br>
        <a href="{{ url_for("administration.user_listing") }}" class="btn btn-primary my-1">{{ LANG_STRINGS.REGISTERED_USER_LIST }}</a>
    </div>
{% endblock %}

clinicmgmt/templates/admin_website_configuration_form.html
{% extends "base.html" %}

{% block HTML_CONTENTS %}
<div class="container">
    <form action="{{ url_for('administration.update_website_config') }}" method="post" enctype="multipart/form-data">
        <p>
            {{ LANG_STRINGS.YOU_MUST_RESTART_TO_APPLY_CHANGES }}
        </p>

        <div class="form-floating my-1">
            <input name="title" type="text" id="title" class="form-control" placeholder="{{ LANG_STRINGS.TITLE }}" value="{{ CONFIG.title }}" required />
            <label for="title">{{ LANG_STRINGS.TITLE }}</label>
        </div>

        <div class="form-floating my-1">
            <select class="form-select" name="language" id="language">
                {% for ONE_LANGUAGE in SUPPORTED_LANGUAGES %}
                    <option value="{{ ONE_LANGUAGE[0] }}"{% if CONFIG.language == ONE_LANGUAGE[0] %} selected{% endif %}>{{ ONE_LANGUAGE[1] }}</option>
                {% endfor %}
            </select>
            <label for="language">{{ LANG_STRINGS.LANGUAGE }}</label>
        </div>

        <div class="form-floating my-1">
            <select class="form-select" name="timezone_str" id="timezone_str">
                {% for TZ_STR in ALL_TIMEZONES %}
                    <option value="{{ TZ_STR }}"{% if CONFIG.timezone_str == TZ_STR %} selected{% endif %}>{{ TZ_STR }}</option>
                {% endfor %}
            </select>
            <label for="timezone_str">{{ LANG_STRINGS.TIMEZONE }}</label>
        </div>

        <div class="form-floating my-1">
            <input type="submit" value="{{ LANG_STRINGS.UPDATE_CONFIGURATION }}" class="btn btn-danger" />
        </div>
    </form>
</div>
{% endblock %}

clinicmgmt/templates/entry_listing.html
{% extends "base.html" %}
{% block HTML_CONTENTS %}
    <section class="bg-dark text-light py-3 mb-2">
            <div class="container">
                {% if USER_CONTEXT %}
                    <a href="{{ url_for("schedule.entry_maker_form") }}" class="btn btn-warning">{{ LANG_STRINGS.ADD_OPERATION}}</a>
                    <a href="{{ url_for("schedule.index_printable", **ARGS_TO_FORWARD) }}" class="btn btn-primary">{{ LANG_STRINGS.PRINTABLE_VERSION }}</a>
                    <a href="{{ url_for("schedule.search_form") }}" class="btn btn-info">{{ LANG_STRINGS.SEARCH}}</a>
                    <a href="{{ url_for("schedule.index", timeframe="all") }}" class="btn btn-danger">{{ LANG_STRINGS.ARCHIVE_AND_FUTURE }}</a>
                    <a href="{{ url_for("schedule.calendar_form") }}" class="btn btn-success">{{ LANG_STRINGS.CALENDAR}}</a>
                {% endif %}
            </div>
    </section>
    <div class="container">
        <h3 class="pb-2">{{ TIMEFRAME_STR }}</h3>
        <div class="entry_listing">
        {% for ENTRY in ENTRIES %}
            <div class="card mb-1 {% if ENTRY.is_completed == 1 %}text-bg-success{% endif %}">
                <a href='{{ url_for("schedule.entry_view", entry_id=ENTRY.entry_id) }}' class="stretched-link"></a>
                <div class="card-body">
                    <h5 class="card-title">
                        {{ ENTRY.patient_name }}
                    </h5>
                    <span class="card-subtitle">
                        {{ ENTRY.type_of_surgery }}
                    </span>
                    <div class="card-text">
                        {{ ENTRY.diagnosis }}
                    </div>
                </div>
                <div class="card-footer">
                    {{ ENTRY.scheduled_timestamp_str }}
                </div>
            </div>
        {% endfor %}
        </div>
    </div>
{% endblock %}

clinicmgmt/templates/entry_view.html
{% extends "base.html" %}

{% block HEAD %}
    <title>{{ ENTRY.patient_name }} - {{ WEBSITE_CONTEXT['title'] }}</title>
{% endblock %}

{% block HTML_CONTENTS %}
    <div class="container">
        {% if ENTRY.is_completed == 1 %}
            <div class='alert alert-success'>
                {{ LANG_STRINGS.THIS_OPERATION_IS_MARKED_AS_COMPLETED }}
            </div>
        {% endif %}

        <div class="entry_title">
            <h2>
                {{ LANG_STRINGS.PATIENT }}: {{ ENTRY.patient_name }}
            {% if ENTRY.patient_birth_year %}({{ ENTRY.patient_birth_year }}){% endif %}
            </h2>
        </div>

        {% if ENTRY.patient_phone_number %}
            <p>{{ LANG_STRINGS.PHONE_NUMBER_SHORT }} {{ ENTRY.patient_phone_number }}</p>
        {% endif %}

        <p>{{ LANG_STRINGS.OPERATION_TIME }}: {{ ENTRY.scheduled_timestamp_str }}</p>

        <p>{{ LANG_STRINGS.TENDING_DOCTOR }}: {{ ENTRY.assigned_doctor_name }}</p>

        {% if ENTRY.has_consultation_happened == 1 %}
            <p>{{ LANG_STRINGS.CONSULTATION_HAS_HAPPENED }}</p>
        {% else %}
            <p>{{ LANG_STRINGS.CONSULTATION_HAS_NOT_HAPPENED }}</p>
        {% endif %}

        <p>{{ ENTRY.type_of_surgery }}</p>

        <p class="entry_contents">
            {{ ENTRY.diagnosis | safe }}
        </p>
    </div>

    <section class="bg-dark text-light py-2">
        <div class="container">
        <h4>{{ LANG_STRINGS.APPROVALS }}</h4>
            {% if USER_CONTEXT.is_approver == 1 %}
                {% if ENTRY.current_user_has_approved == 1 %}
                    <a href='{{ url_for("schedule.mark_entry_disapproved", entry_id=ENTRY.entry_id) }}' class="btn btn-warning mb-1">{{ LANG_STRINGS.RETRACT_APPROVAL }}</a>
                {% else %}
                    <a href='{{ url_for("schedule.mark_entry_approved", entry_id=ENTRY.entry_id) }}' class="btn btn-primary mb-1">{{ LANG_STRINGS.GIVE_APPROVAL }}</a>
                {% endif %}
            {% endif %}

            {% for APPROVER in ENTRY.approvers %}
                <p>
                    {{ APPROVER.display_name }} ({{ LANG_STRINGS.DATE_GIVEN}}: {{ APPROVER.approval_timestamp_str }})
                </p>
            {% endfor %}
        </div>
    </section>

    <section class="bg-light text-dark py-2">
        <div class="container">
            {% if ENTRY.is_completed == 1 %}
                <a href='{{ url_for("schedule.mark_entry_incomplete", entry_id=ENTRY.entry_id) }}' class="btn btn-warning">{{ LANG_STRINGS.MARK_AS_INCOMPLETE }}</a>
            {% else %}
                <a href='{{ url_for("schedule.mark_entry_completed", entry_id=ENTRY.entry_id) }}' class="btn btn-primary">{{ LANG_STRINGS.MARK_AS_COMPLETED }}</a>
            {% endif %}

            <a href='{{ url_for("schedule.entry_edit_form", entry_id=ENTRY.entry_id) }}' class="btn btn-secondary">{{ LANG_STRINGS.EDIT }}</a>
            <a href='{{ url_for("schedule.delete_entry", entry_id=ENTRY.entry_id) }}' class="btn btn-danger">{{ LANG_STRINGS.DELETE }}</a>
            <p>
                {{ LANG_STRINGS.INFORMATION_AUTHOR }}: <a href='{{ url_for("schedule.index", timeframe="search", author_id=ENTRY.author.id) }}' class="text-primary">
                {{ ENTRY.author.display_name }}</a>
            </p>
            <p>{{ LANG_STRINGS.INFORMATION_ADDED_AT }}: {{ ENTRY.added_timestamp_str }}</p>
            {% if ENTRY.added_timestamp_timestamp_str != ENTRY.last_edited_timestamp_str %}
                <p>{{ LANG_STRINGS.INFORMATION_LAST_UPDATED_AT }}: {{ ENTRY.last_edited_timestamp_str }}</p>
            {% endif %}
        </div>
    </section>
{% endblock %}

clinicmgmt/templates/sql.html
{% extends "base.html" %}

{% block HTML_CONTENTS %}
    <div class="container">
        <form action="{{ url_for("administration.sql_exec") }}" method="POST">
            <div class="form-floating my-1">
                <textarea rows="4" style="height:40%;" name="sql_query" type="text" id="sql_query" class="form-control" placeholder="{{ LANG_STRINGS.SQL_QUERY_GOES_HERE }}" required></textarea>
                <label for="sql_query">{{ LANG_STRINGS.SQL_QUERY_GOES_HERE }}</label>
            </div>

            <div class="form-floating my-1">
                <input type="submit" value="{{ LANG_STRINGS.EXECUTE }}" class="btn btn-primary" />
            </div>
        </form>

        {% if SQL_RESULTS %}
            <br>
            <div class="form-floating">
                <textarea rows="4" style="height:40%;" name="query_results" type="text" id="query_results" class="form-control" placeholder="{{ LANG_STRINGS.EXECUTION_RESULTS }}" required>{{ SQL_RESULTS }}</textarea>
                <label for="query_results">{{ LANG_STRINGS.EXECUTION_RESULTS }}</label>
            </div>
        {% endif %}
    </div>
{% endblock %}

clinicmgmt/templates/user_listing.html
{% extends "base.html" %}

{% block HTML_CONTENTS %}
    {% if USER_CONTEXT.is_administrator == 1 %}
        <section class="bg-dark text-light py-3 mb-2">
            <div class="container">
                <a href="{{ url_for("user_management.member_invite_form") }}" class="btn btn-warning">{{ LANG_STRINGS.INVITE_USER }}</a>
                <a href="{{ url_for("user_management.member_invite_listing") }}" class="btn btn-info">{{ LANG_STRINGS.INVITED_USER_LIST }}</a>
            </div>
        </section>
    {% endif %}

    <div class="container">
        <div class="row">
            {% for info in USER_LISTING %}
                <div class="col-6 col-sm-6 col-md-6 col-lg-4 col-xl-3 col-xxl-3 mb-3">
                    <div class="card">
                        <!--img class="card-img-top" src="{{ url_for('static', filename='default_pp.png') }}" alt="Card image cap"-->
                        <div class="card-body">
                            <h5 class="card-title">{{ info[2] }}</h5>
                            <h6 class="card-subtitle mb-2 text-muted">{{ info[1] }}</h6>
                            {% if info[3] == 1 %}
                                <strong class="card-text">{{ LANG_STRINGS.ADMINISTRATOR }}</strong><br>
                            {% endif %}
                            <a href="{{ url_for("schedule.index", timeframe="search", author_id=info[0]) }}" class="btn btn-primary mt-2">{{ LANG_STRINGS.ADDED_OPERATIONS }}</a>
                            <a href="{{ url_for("schedule.index", timeframe="search", assigned_doctor_name=info[2]) }}" class="btn btn-primary mt-2">{{ LANG_STRINGS.LINKED_OPERATIONS }}</a>
                            {% if USER_CONTEXT.is_administrator == 1 %}
                                <a href="{{ url_for("user_management.administrator_password_recovery_form", user_id=info[0]) }}"
                                   class="btn btn-danger mt-2">{{ LANG_STRINGS.CHANGE_PASSWORD }}</a>
                                <a href="{{ url_for("user_management.administrator_account_editing_form", user_id=info[0]) }}"
                                   class="btn btn-danger mt-2">{{ LANG_STRINGS.EDIT_PROFILE }}</a>
                                <a href="{{ url_for("user_management.administrator_account_deletion_form", user_id=info[0]) }}"
                                   class="btn btn-danger mt-2">{{ LANG_STRINGS.DELETE_ACCOUNT }}</a>
                            {% endif %}
                        </div>
                        {% if USER_CONTEXT.is_administrator == 1 %}
                            <div class="card-footer">
                                UUID: {{ info[0] }}
                            </div>
                        {% endif %}
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}